[[cards]]
title = "Setting up CUPS on Linux"
code = """
yay -S cups
systemctl enable org.cups.cupsd.service
systemctl start org.cups.cupsd.service
sudo usermod -a -G sys jayden
xdg-open http://localhost:631
"""
language = "bash"
tags = [ "linux", "printing", "CUPS" ]

[[cards]]
title = "Show GPU information"
code = "lspci -vnn | rg VGA -A 12"
language = "bash"
tags = [ "linux", "sysinfo" ]

[[cards]]
title = "retain all lines matching a pattern"
code = """
:v/pattern/d
"""
language = "vim"
tags = [ "vim", "command", "regex" ]

[[cards]]
title = "delete all lines matching pattern"
code = """
:g/pattern/d
"""
language = "vim"
tags = [ "vim", "command", "regex" ]
