title = "Linux / Vim"

[[cards]]
title = "[Linux] Pipe command output to clipboard"
code = "command | xclip -selection c"
language = "bash"
tags = [ "linux", "clipboard", "pipe", "command" ]

[[cards]]
title = "[Linux] Convert JPGs to PDF"
code = "convert 1.jpg 2.jpg -rotate 90 -page Letter -quality 50 out.pdf"
language = "bash"
tags = [ "linux", "convert" ]

[[cards]]
title = "[Linux] Concatenate PDFs"
code = "pdftk one.pdf two.pdf cat output combined.pdf"
language = "bash"
tags = [ "linux", "concat" ]

[[cards]]
title = "[Linux] Show disk space usage for current folder"
code = "du -sch *  | sort -h"
language = "bash"
tags = [ "linux", "disk" ]

[[cards]]
title = "[Linux] Remap caps lock to escape"
code = """
xmodmap -e "clear lock"
xmodmap -e "keysym Caps_Lock = Escape"
"""
language = "bash"
tags = [ "linux" ]

[[cards]]
title = "[Linux] Change key repeat rate and delay"
code = "xset r rate 270 35"
language = "bash"
tags = [ "linux" ]

[[cards]]
title = "[Linux] Setting up CUPS"
code = """
yay -S cups
systemctl enable org.cups.cupsd.service
systemctl start org.cups.cupsd.service
sudo usermod -a -G sys jayden # Prevent forbidden errors
xdg-open http://localhost:631
"""
struggle = true
language = "bash"
tags = [ "linux", "printing", "CUPS" ]

[[cards]]
title = "[Linux] Show GPU information"
code = "lspci -vnn | rg VGA -A 12"
tags = [ "linux", "sysinfo" ]

[[cards]]
title = "[Git] Show the total number of commits"
code = "git rev-list --count --all"
tags = [ "git" ]

[[cards]]
title = "[Vim] Retain all lines matching a pattern"
code = """
:v/pattern/d
"""
tags = [ "vim", "command", "regex" ]

[[cards]]
title = "[Vim] Delete all lines matching pattern"
code = """
:g/pattern/d
"""
tags = [ "vim", "command", "regex" ]

[[cards]]
title = "[Linux] Change the timezone"
code = "timedatectl set-timezone Canada/Mountain"
tags = [ "oneliners", "linux" ]
