title = "Linux / Vim"

[[cards]]
title = "[Linux] Setting up CUPS"
code = """
yay -S cups
systemctl enable org.cups.cupsd.service
systemctl start org.cups.cupsd.service
sudo usermod -a -G sys jayden # Prevent forbidden errors
xdg-open http://localhost:631
"""
struggle = true
language = "bash"
tags = [ "linux", "printing", "CUPS" ]

[[cards]]
title = "[Linux] Show GPU information"
code = "lspci -vnn | rg VGA -A 12"
tags = [ "linux", "sysinfo" ]

[[cards]]
title = "[Git] Show the total number of commits"
code = "git rev-list --count --all"
tags = [ "git" ]

[[cards]]
title = "[Vim] Retain all lines matching a pattern"
code = """
:v/pattern/d
"""
tags = [ "vim", "command", "regex" ]

[[cards]]
title = "[Vim] Delete all lines matching pattern"
code = """
:g/pattern/d
"""
tags = [ "vim", "command", "regex" ]
