interests = [
  "Coffee",
  "Cooking",
  "Mechanical Keyboards",
  "Gaming",
]

[skills]
lang = [ "JavaScript / TypeScript", "Rust", "C", "Go", "HTML / CSS / SCSS" ]
tools = [ "Git", "Linux", "bash / zsh", "Vim", "LaTeX" ]
tech = [
  "React / React Native",
  "Webpack",
  "Heroku",
  "Google Cloud Platform",
  "PostgreSQL / MySQL / MariaDB",
  "REST / GraphQL",
]

[[experience]]
print = true
title = "Software Developer"
location = "Victoria, Canada"
company = "Referral SaaSquatch"
time = "Jan 2019 - Apr 2020"
roles = [
  "Developed core logic for the SaaSquatch Growth Automation platform with using Express, Heroku, and Contentful",
  "Implemented a new frontend build process from scratch using Babel & Webpack, adding TypeScript support and reducing build times from ~2 minutes to 400 ms",
  "Helped migrate the SaaSquatch analytics backend from Keen to BigQuery, including a custom query server to translate Keen API calls into BigQuery SQL",
  "Created a NodeJS command line program for compiling Gherkin specification documents into spreadsheets for manual QA"
]

[[experience]]
print = true
title = "Robotics Software Technician"
location = "Calgary, Canada"
company = "Bickert Robotics"
time = "Apr 2018 - Sep 2018"
roles = [
  "Developed a software suite to power Bickert Robotics' automated bartender robot",
  "Implemented a REST API using Go and PostgreSQL for managing drink recipes, ingredients, robot configurations, and customer credentials",
  "Developed an Android app for directly controlling the robot using Java and the Android SDK",
  "Designed a web app for viewing / editing drinks, users, and tanks using React. Included page for viewing the drink queue on the robot's embedded display",
  "Wrote embedded Python code to receive user input and autonomously pour drinks based on JSON recipe data"
]

# [[experience]]
# print = false
# title = "Programming Team Leader"
# location = "Calgary, Canada"
# company = "Alberta Tech Alliance Association"
# time = "Oct 2015 - Oct 2016"
# roles = [
#   "Led a team of developers in the creation of embedded robot code for the F.I.R.S.T Robotics Competition",
#   "Developed robust and performant software using Java, C# and the WPI robotics libraries",
#   "Participated in and won the annual China Robotics Challenge in 2016. Provided mentorship and advice to rookie Chinese teams before the competition"
# ]

[[projects]]
print = true
title = "Nit"
stack = "Rust"
github = "nit"
time = "2019-present"
roles = [
  "Nit is a physically-based raytracer built with Rust",
  "Uses a Monte-Carlo path-tracing approach to rendering realistic scenes based on the physical properties of light",
  "Implements a sub-linear collision detection algorithm with a Bounding-Volume Hierarchy",
  "Supports loading polygon meshes from STL files",
  "Parallelized across any number of CPU cores"
]

[[projects]]
print = false
title = "Battlesnake"
stack = "Rust / Go"
time = "2019"
roles = [
  "Developed an artificial intelligence to compete in the Battlesnake programming competition",
  "Uses parallel Monte-Carlo Tree Search for assessing future game states",
  "Implemented a variety of other common algorithms for use in the Monte-Carlo rollout phase",
  "Created a moving-average analyzer to match other snakes' behavior to a profile"
]

[[projects]]
print = true
title = "ESS Locker System"
stack = "Node / React / MySQL"
github = "ess-lockers"
time = "2018 - present"
roles = [
  "Developed a web app for managing the UVic Engineering Student Society locker rental system",
  "Migrated 6 year-old legacy PHP code to Node.js and created a more secure, email-based authentication system for removing locker registrations",
  "Modernized front-end interface with React + Bootstrap",
  "Integrated Contentful with the backend to provide an ergonomic content management workflow for ESS executives"
]

[[projects]]
print = false
title = "UVic ENGR 120 Design Project"
stack = "C"
github = "ENGR120-Vex"
time = "2018"
roles = [
  "Designed and built a small prototype robot for connecting wires on the ocean floor",
  "Created and programmed a rotating photosensor mechanism to detect the attachment point",
  "Implemented PID and slew rate controllers for quickly and smoothly driving to the attachment point",
  "Participated in a course-wide competition and placed 1st with an average connection time of 5.99 seconds"
]

[[awards]]
result = "Winner"
time = "2020"
desc = "Western Engineering Competition (Programming)"

[[awards]]
result = "Winner"
time = "2018, 2019"
desc = "UVic Engineering Competition (Programming)"

[[awards]]
result = "Winner"
time = "2018"
desc = "UVic ENGR 120 Design Competition"

[[awards]]
result = "Winner"
time = "2016"
desc = "Western Canada Regional Robotics Competition"

[[awards]]
result = "Winner"
time = "2016"
desc = "China Robotics Challenge"

[[awards]]
result = "Innovation in Control Award"
time = "2015, 2016"
desc = "Western Canada Regional Robotics Competition"
