interests = [
  "Cooking",
  "Coffee",
  "Mechanical Keyboards",
  "Gaming",
]

[skills]
lang = [ "JavaScript / TypeScript", "Rust", "Go", "C", "HTML / CSS / SCSS" ]
tools = [ "Git", "Linux", "bash / zsh", "Vim", "LaTeX" ]
tech = [
  "React / React Native",
  "Webpack",
  "Heroku",
  "Google Cloud Platform",
  "PostgreSQL / MySQL / MariaDB",
  "REST / GraphQL",
]

[[experience]]
print = true
title = "Software Developer"
location = "Victoria, Canada"
company = "Referral SaaSquatch"
time = "Jan 2019 - present"
roles = [
  "Developed core logic for the SaaSquatch Growth Automation platform using Contentful and the Auth0 Extend serverless platform.",
  "Implemented a new frontend build process from scratch using Babel & Webpack, enabling the use of TypeScript and reducing build times from ~2 minutes to 400 ms",
  "Custom-built a command line tool for easily deploying updates to the Contentful & Extend staging environments, as well as for performing monitoring and synchronization.",
  "Helped migrate the SaaSquatch analytics engine backend from Keen to BigQuery, including data verification / validation and a custom query server to translate Keen API calls into BigQuery SQL queries."
]

[[experience]]
print = true
title = "Robotics Software Technician"
location = "Calgary, Canada"
company = "Bickert Robotics"
time = "Apr 2018 - Sep 2018"
roles = [
  "Developed a software suite to power Bickert Robotics' automated bartender robot",
  "Implemented a REST API using Go and PostgreSQL to perform CRUD operations on drink recipes, ingredients, robot configurations, and customer credentials",
  "Developed an Android app for directly controlling the robot using Java and the Android SDK",
  "Designed a web app for viewing / editing drinks, users, and tanks using React. Included page for viewing the drink queue on the robot's embedded display",
  "Wrote embedded Python code to receive user input and autonomously pour drinks based on JSON recipe data"
]

# [[experience]]
# print = false
# title = "Programming Team Leader"
# location = "Calgary, Canada"
# company = "Alberta Tech Alliance Association"
# time = "Oct 2015 - Oct 2016"
# roles = [
#   "Led a team of developers in the creation of embedded robot code for the F.I.R.S.T Robotics Competition",
#   "Developed robust and performant software using Java, C# and the WPI robotics libraries",
#   "Participated in and won the annual China Robotics Challenge in 2016. Provided mentorship and advice to rookie Chinese teams before the competition"
# ]

[[projects]]
print = true
title = "YARR"
stack = "Rust"
github = "yarr"
time = "2019"
roles = [
  "YARR is a physically-based raytracer built with Rust",
  "A Monte-Carlo path-tracing approach to rendering realistic scenes based on the physical properties of light",
  "Supports matte, reflective and glass surfaces",
  "Axis-aligned bounding box-based BVH for accelerating collision detections"
]

[[projects]]
print = true
title = "Battlesnake"
stack = "Rust / Go"
time = "2019"
roles = [
  "Developed an artificial intelligence to compete in the Battlesnake programming competition",
  "Designed a simulation-based algorithm that assesses future game states and selects the most appropriate move",
  "Implemented a variety of other common algorithms to provide more realistic simulation branches for the main AI",
  "Created a simple analytics engine that monitors the moves of other snakes, looking for patterns in their behavior. The output of the engine is fed into the main simulation to increase its accuracy.",
  "Created a simple HTTP server to respond to POST requests from the main game server"
]

[[projects]]
print = true
title = "ESS Locker System"
stack = "Node / React / MySQL"
github = "ess-lockers"
time = "2018 - present"
roles = [
  "Developed a web app for managing the UVic Engineering Student Society locker rental system",
  "Migrated 6 year-old legacy PHP code to Node.js and created a more secure, email-based authentication system for removing locker registrations",
  "Modernized front-end interface with React + Bootstrap",
  "Integrated Contentful with the backend to provide an ergonomic content management workflow for ESS executives"
]

[[projects]]
print = false
title = "UVic ENGR 120 Design Project"
stack = "C"
github = "ENGR120-Vex"
time = "2018"
roles = [
  "Designed and built a small prototype robot for connecting wires on the ocean floor",
  "Created and programmed a rotating photosensor mechanism to detect the attachment point",
  "Implemented PID and slew rate controllers for quickly and smoothly driving to the attachment point",
  "Participated in a course-wide competition and placed 1st with an average connection time of 5.99 seconds"
]

[[awards]]
result = "Winner"
time = "2018, 2019"
desc = "UVic Engineering Competition (Programming)"

[[awards]]
result = "Winner"
time = "2016"
desc = "Western Canada Regional Robotics Competition"

[[awards]]
result = "Winner"
time = "2016"
desc = "China Robotics Challenge"

[[awards]]
result = "Innovation in Control Award"
time = "2015, 2016"
desc = "Western Canada Regional Robotics Competition"
