[[games]]
date = "Jul 30. 2020"
map = "Haven"
score = [ 13, 0 ]
time = "24:17"
url = "https://www.youtube.com/watch?v=aN7kK0vym5Q"
scoreboard = [
  [ "breach", "ATQMIC", "482", "25", "6", "4", "131", "3", "0", "0" ],
  [ "phoenix", "stotz", "347", "14", "13", "3", "72", "0", "0", "0" ],
  [ "cypher", "HonestPretzels", "276", "14", "7", "3", "72", "5", "1", "0" ],
  [ "sage", "Eung Coconut", "243", "12", "4", "5", "92", "2", "0", "3" ],
  [ "sova", "Wild West", "191", "8", "5", "7", "75", "2", "0", "0" ],
  [ "sova", "Titoad", "169", "7", "13", "3", "39", "0", "1", "0" ],
  [ "omen", "Jakyb", "140", "7", "6", "4", "55", "1", "0", "1" ],
  [ "omen", "Gravidi", "91", "3", "13", "0", "22", "0", "1", "0" ],
  [ "cypher", "SSL", "68", "3", "14", "0", "15", "0", "0", "0" ],
  [ "sage", "SkrubLawd", "43", "1", "13", "6", "16", "0", "2", "0" ],
]

[[games]]
date = "Jul 30. 2020"
map = "Split"
score = [ 6, 13 ]
time = "39:31"
url = "https://www.youtube.com/watch?v=YsbT0IVeceg"
scoreboard = [
  [ "raze", "ATQMIC", "380", "25", "12", "5", "106", "5", "2", "0" ],
  [ "phoenix", "stotz", "339", "21", "14", "7", "93", "6", "3", "0" ],
  [ "sova", "Titoad", "301", "20", "9", "4", "89", "0", "4", "2" ],
  [ "cypher", "HonestPretzels", "192", "13", "16", "5", "42", "2", "0", "0" ],
  [ "sage", "SkrubLawd", "180", "14", "13", "6", "36", "1", "0", "0" ],
  [ "brimstone", "Wild West", "165", "9", "15", "4", "54", "1", "0", "1" ],
  [ "omen", "Gravidi", "129", "7", "16", "3", "46", "1", "2", "0" ],
  [ "sage", "Eung Coconut", "126", "9", "13", "10", "53", "1", "1", "0" ],
  [ "cypher", "SSL", "101", "7", "11", "4", "32", "0", "0", "1" ],
  [ "omen", "Jakyb", "91", "6", "16", "2", "51", "2", "2", "0" ],
]


[[games]]
date = "Jul 30. 2020"
map = "Bind"
score = [ 13, 11 ]
time = "49:02"
url = "https://www.youtube.com/watch?v=hglYaHR4rUs"
scoreboard = [
  [ "omen", "WoodenTusk", "356", "31", "17", "5", "91", "4", "0", "2" ],
  [ "brimstone", "LithiumFrost", "297", "27", "16", "7", "99", "3", "6", "2" ],
  [ "phoenix", "stotz", "264", "21", "19", "8", "64", "3", "1", "0" ],
  [ "cypher", "HonestPretzels", "233", "22", "18", "3", "46", "0", "1", "1" ],
  [ "sova", "Titoad", "209", "16", "17", "8", "53", "1", "0", "2" ],
  [ "phoenix", "ATQMIC", "203", "16", "16", "10", "52", "4", "1", "0" ],
  [ "sage", "Eung Coconut", "201", "14", "19", "11", "42", "1", "0", "1" ],
  [ "sova", "Wild West", "195", "16", "16", "8", "71", "3", "0", "0" ],
  [ "sage", "Gravidi", "102", "9", "18", "5", "30", "2", "6", "0" ],
  [ "jett", "SoulDrinker27", "101", "6", "24", "9", "26", "3", "0", "0" ],
]

[[games]]
date = "Jul 25. 2020"
map = "Ascent"
score = [ 3, 13 ]
time = "35:00"
url = "https://www.youtube.com/watch?v=2sjITXAO8Qs"
scoreboard = [
  [ "brimstone", "bluelightsaber", "300", "18", "8", "0", "65", "3", "0", "0" ],
  [ "viper", "wx3", "267", "15", "9", "4", "69", "3", "2", "0" ],
  [ "brimstone", "LithiumFrost", "262", "15", "14", "3", "69", "2", "1", "0" ],
  [ "omen", "l3gsh0t", "240", "13", "10", "3", "60", "2", "1", "0" ],
  [ "cypher", "Ragnar", "236", "14", "6", "4", "114", "0", "0", "0" ],
  [ "raze", "dootcher", "181", "11", "6", "2", "51", "1", "1", "0" ],
  [ "sova", "Eung Coconut", "162", "9", "13", "2", "48", "1", "0", "1" ],
  [ "sage", "Pax1", "128", "5", "13", "5", "38", "1", "1", "0" ],
  [ "cypher", "HonestPretzels", "104", "6", "15", "0", "29", "2", "0", "0" ],
  [ "phoenix", "ATQMIC", "82", "4", "16", "3", "15", "1", "0", "0" ],
]

[[games]]
date = "Jul 25. 2020"
map = "Bind"
score = [ 13, 3 ]
time = "33:01"
url = "https://www.youtube.com/watch?v=kT9419yH86s"
scoreboard = [
  [ "sova", "Eung Coconut", "364", "21", "5", "5", "146", "4", "0", "0" ],
  [ "phoenix", "ATQMIC", "308", "19", "8", "3", "79", "1", "1", "1" ],
  [ "brimstone", "bluelightsaber", "241", "12", "13", "1", "55", "0", "0", "0" ],
  [ "brimstone", "LithiumFrost", "194", "12", "10", "1", "53", "3", "5", "0" ],
  [ "sova", "Ragnar", "191", "9", "15", "2", "46", "0", "0", "0" ],
  [ "cypher", "HonestPretzels", "169", "9", "11", "5", "41", "2", "0", "0" ],
  [ "phoenix", "dootcher", "157", "8", "13", "3", "43", "3", "2", "0" ],
  [ "omen", "l3gsh0t", "146", "8", "14", "2", "39", "2", "0", "0" ],
  [ "viper", "wx3", "124", "4", "11", "3", "46", "1", "0", "0" ],
  [ "sage", "Pax1", "90", "5", "8", "9", "52", "0", "0", "1" ],
]

[[games]]
date = "Jul 25. 2020"
map = "Haven"
score = [ 5, 13 ]
time = "36:36"
url = "https://www.youtube.com/watch?v=4NIc6c7WZvI"
scoreboard = [
  [ "sova", "l3gsh0t", "324", "21", "10", "6", "79", "1", "2", "0" ],
  [ "omen", "ATQMIC", "288", "18", "17", "1", "92", "2", "0", "0" ],
  [ "sage", "CJames11", "246", "16", "12", "5", "52", "2", "1", "0" ],
  [ "brimstone", "bluelightsaber", "245", "15", "9", "3", "68", "3", "1", "0" ],
  [ "viper", "wx3", "214", "14", "8", "6", "51", "2", "5", "0" ],
  [ "sage", "Pax1", "213", "11", "15", "5", "56", "0", "0", "0" ],
  [ "cypher", "HonestPretzels", "192", "10", "16", "9", "55", "3", "0", "1" ],
  [ "phoenix", "Ragnar", "176", "12", "14", "2", "45", "4", "0", "0" ],
  [ "brimstone", "LithiumFrost", "128", "8", "16", "4", "72", "1", "1", "1" ],
  [ "phoenix", "Eung Coconut", "101", "6", "16", "4", "28", "0", "0", "0" ],
]
